<?php

use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\AccountTransferController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BrapiQuoteController;
use App\Http\Controllers\Api\BudgetController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\CreditCardController;
use App\Http\Controllers\Api\CreditCardInvoiceController;
use App\Http\Controllers\Api\CreditCardPurchaseController;
use App\Http\Controllers\Api\FinancialCommitmentController;
use App\Http\Controllers\Api\InvestmentController;
use App\Http\Controllers\Api\MerchantController;
use App\Http\Controllers\Api\MonthlySummaryController;
use App\Http\Controllers\Api\OpenFinanceController;
use App\Http\Controllers\Api\PlanningSummaryController;
use App\Http\Controllers\Api\RecurringTransactionController;
use App\Http\Controllers\Api\Slice5Controller;
use App\Http\Controllers\Api\TransactionController;
use App\Http\Controllers\Api\TransactionReversalController;
use App\Http\Controllers\Api\WalletController;
use App\Http\Controllers\Api\WalletMemberController;
use App\Http\Resources\UserResource;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::post('/auth/login', [AuthController::class, 'store']);
Route::post('/auth/register', [AuthController::class, 'register']);
Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/auth/reset-password', [AuthController::class, 'resetPassword']);

Route::get('/user', function (Request $request) {
    return new UserResource($request->user());
})->middleware('auth:sanctum');

Route::post('/open-finance/webhook', [OpenFinanceController::class, 'webhook'])->name('api.open-finance.webhook');

Route::middleware('auth:sanctum')->group(function (): void {
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::post('/auth/logout-all', [AuthController::class, 'logoutAll']);
    Route::get('/auth/tokens', [AuthController::class, 'tokens']);
    Route::delete('/auth/tokens/{token}', [AuthController::class, 'revokeToken'])->whereNumber('token');
    Route::post('/wallets', [WalletController::class, 'store']);
    Route::get('/wallets', [WalletController::class, 'index']);
    Route::patch('/wallets/{wallet}', [WalletController::class, 'update'])->whereNumber('wallet');
    Route::get('/wallets/{wallet}/members', [WalletMemberController::class, 'index'])->whereNumber('wallet');
    Route::post('/wallets/{wallet}/members', [WalletMemberController::class, 'store'])->whereNumber('wallet');
    Route::patch('/wallets/{wallet}/members/{member}', [WalletMemberController::class, 'update'])->whereNumber('wallet')->whereNumber('member');
    Route::delete('/wallets/{wallet}/members/{member}', [WalletMemberController::class, 'destroy'])->whereNumber('wallet')->whereNumber('member');
    Route::post('/accounts', [AccountController::class, 'store']);
    Route::get('/accounts', [AccountController::class, 'index']);
    Route::patch('/accounts/{account}', [AccountController::class, 'update'])->whereNumber('account');
    Route::post('/categories', [CategoryController::class, 'store']);
    Route::get('/categories', [CategoryController::class, 'index']);
    Route::patch('/categories/{category}', [CategoryController::class, 'update'])->whereNumber('category');
    Route::post('/merchants', [MerchantController::class, 'store']);
    Route::get('/merchants', [MerchantController::class, 'index']);
    Route::post('/transactions', [TransactionController::class, 'store']);
    Route::put('/transactions/{transaction}', [TransactionController::class, 'update'])->whereNumber('transaction');
    Route::patch('/transactions/{transaction}', [TransactionController::class, 'update'])->whereNumber('transaction');
    Route::delete('/transactions/{transaction}', [TransactionController::class, 'destroy'])->whereNumber('transaction');
    Route::post('/transactions/{transaction}/reversal', [TransactionReversalController::class, 'store'])->whereNumber('transaction');
    Route::post('/account-transfers', [AccountTransferController::class, 'store']);
    Route::get('/transactions', [TransactionController::class, 'index']);
    Route::get('/monthly-summary', MonthlySummaryController::class);
    Route::post('/credit-cards', [CreditCardController::class, 'store']);
    Route::get('/credit-cards', [CreditCardController::class, 'index']);
    Route::get('/credit-cards/{creditCard}/transactions', [CreditCardController::class, 'transactions'])->whereNumber('creditCard');
    Route::put('/credit-cards/{creditCard}', [CreditCardController::class, 'update'])->whereNumber('creditCard');
    Route::delete('/credit-cards/{creditCard}', [CreditCardController::class, 'destroy'])->whereNumber('creditCard');
    Route::post('/credit-card-purchases', [CreditCardPurchaseController::class, 'store']);
    Route::put('/credit-card-purchases/{purchase}', [CreditCardPurchaseController::class, 'update'])->whereNumber('purchase');
    Route::delete('/credit-card-purchases/{purchase}', [CreditCardPurchaseController::class, 'destroy'])->whereNumber('purchase');
    Route::put('/credit-card-transactions/{transaction}', [CreditCardPurchaseController::class, 'updateInstallment'])->whereNumber('transaction');
    Route::delete('/credit-card-transactions/{transaction}', [CreditCardPurchaseController::class, 'destroyInstallment'])->whereNumber('transaction');
    Route::get('/credit-card-invoices', [CreditCardInvoiceController::class, 'index']);
    Route::post('/credit-card-invoices/{invoice}/close', [CreditCardInvoiceController::class, 'close'])->whereNumber('invoice');
    Route::post('/credit-card-invoices/{invoice}/payments', [CreditCardInvoiceController::class, 'pay'])->whereNumber('invoice');
    Route::post('/recurring-transactions', [RecurringTransactionController::class, 'store']);
    Route::get('/recurring-transactions', [RecurringTransactionController::class, 'index']);
    Route::put('/recurring-transactions/{recurring}', [RecurringTransactionController::class, 'update'])->whereNumber('recurring');
    Route::delete('/recurring-transactions/{recurring}', [RecurringTransactionController::class, 'destroy'])->whereNumber('recurring');
    Route::post('/recurring-transactions/{recurring}/generate', [RecurringTransactionController::class, 'generate'])->whereNumber('recurring');
    Route::post('/financial-commitments', [FinancialCommitmentController::class, 'store']);
    Route::get('/financial-commitments', [FinancialCommitmentController::class, 'index']);
    Route::put('/financial-commitments/{commitment}', [FinancialCommitmentController::class, 'update'])->whereNumber('commitment');
    Route::delete('/financial-commitments/{commitment}', [FinancialCommitmentController::class, 'destroy'])->whereNumber('commitment');
    Route::post('/financial-commitments/{commitment}/generate', [FinancialCommitmentController::class, 'generate'])->whereNumber('commitment');
    Route::post('/budgets', [BudgetController::class, 'store']);
    Route::get('/budgets', [BudgetController::class, 'index']);
    Route::put('/budgets/{budget}', [BudgetController::class, 'update'])->whereNumber('budget');
    Route::delete('/budgets/{budget}', [BudgetController::class, 'destroy'])->whereNumber('budget');
    Route::get('/planning-summary', PlanningSummaryController::class);
    Route::post('/open-finance/connect-token', [OpenFinanceController::class, 'connectToken']);
    Route::post('/open-finance/connections/{connection}/sync', [OpenFinanceController::class, 'sync'])->whereNumber('connection');
    Route::get('/open-finance/items', [OpenFinanceController::class, 'index']);
    Route::post('/open-finance/items', [OpenFinanceController::class, 'store']);
    Route::delete('/open-finance/items/{item}', [OpenFinanceController::class, 'destroy'])->whereNumber('item');
    Route::get('/market/quote', BrapiQuoteController::class);
    Route::apiResource('investments', InvestmentController::class)->except(['show']);
    Route::get('/investment-income', [InvestmentController::class, 'income']);
    Route::get('/investments/{investment}/yields', [InvestmentController::class, 'yields'])->whereNumber('investment');
    Route::post('/consolidations', [Slice5Controller::class, 'createConsolidation']);
    Route::get('/consolidations', [Slice5Controller::class, 'listConsolidations']);
    Route::put('/consolidations/{consolidation}', [Slice5Controller::class, 'updateConsolidation'])->whereNumber('consolidation');
    Route::delete('/consolidations/{consolidation}', [Slice5Controller::class, 'deleteConsolidation'])->whereNumber('consolidation');
    Route::get('/consolidations/{consolidation}/summary', [Slice5Controller::class, 'consolidationSummary'])->whereNumber('consolidation');
    Route::post('/financial-goals', [Slice5Controller::class, 'createGoal']);
    Route::get('/financial-goals', [Slice5Controller::class, 'listGoals']);
    Route::put('/financial-goals/{goal}', [Slice5Controller::class, 'updateGoal'])->whereNumber('goal');
    Route::delete('/financial-goals/{goal}', [Slice5Controller::class, 'deleteGoal'])->whereNumber('goal');
    Route::post('/financial-goals/{goal}/contributions', [Slice5Controller::class, 'contributeToGoal'])->whereNumber('goal');
    Route::post('/tags', [Slice5Controller::class, 'createTag']);
    Route::get('/tags', [Slice5Controller::class, 'listTags']);
    Route::post('/transactions/{transaction}/tags', [Slice5Controller::class, 'tagTransaction'])->whereNumber('transaction');
    Route::post('/transactions/{transaction}/attachments', [Slice5Controller::class, 'uploadAttachment'])->whereNumber('transaction');
    Route::get('/transactions/{transaction}/attachments', [Slice5Controller::class, 'listAttachments'])->whereNumber('transaction');
    Route::post('/attachments', [Slice5Controller::class, 'uploadGenericAttachment']);
    Route::get('/attachments', [Slice5Controller::class, 'listGenericAttachments']);
    Route::get('/attachments/{attachment}/download', [Slice5Controller::class, 'downloadAttachment'])->whereNumber('attachment');
    Route::delete('/attachments/{attachment}', [Slice5Controller::class, 'deleteAttachment'])->whereNumber('attachment');
    Route::get('/notifications', [Slice5Controller::class, 'listNotifications']);
    Route::patch('/notifications/{notification}/read', [Slice5Controller::class, 'readNotification'])->whereNumber('notification');
    Route::post('/imports', [Slice5Controller::class, 'import']);
    Route::get('/imports/{import}', [Slice5Controller::class, 'importBatch'])->whereNumber('import');
});
