import { Badge, Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'flowbite-react';
import { ArrowDownLeft, ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, ReceiptText } from 'lucide-react';
import CreditCardIcon from './CreditCardIcon';
import { formatDateBR } from '@/Utils/date';

const money = (cents) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(cents || 0) / 100);
const statusOptions = [{ value: '', label: 'Todos os status' }, { value: 'POSTED', label: 'Realizadas' }, { value: 'PROJECTED', label: 'Previstas' }, { value: 'CANCELLED', label: 'Canceladas' }];

export default function CreditCardTransactionsModal({ card, transactions, meta, loading, error, filters, onClose, onFilter, onPage }) {
    return <Modal show={Boolean(card)} onClose={onClose} dismissible={!loading} size="4xl">
        <ModalHeader><div className="flex items-center gap-3"><CreditCardIcon institution={card?.institution} /><span><span className="block text-xs font-bold uppercase tracking-wider text-orbital-text-secondary">Movimentos do cartão</span><span className="block text-lg font-bold text-orbital-primary-dark">{card?.name}</span></span></div></ModalHeader>
        <ModalBody>
            <div className="mb-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-orbital-text-primary">Competência<input type="month" value={filters.month} onChange={(event) => onFilter('month', event.target.value)} className="mt-1 block w-full rounded-lg border-orbital-border bg-orbital-surface px-3 py-2 text-sm focus:border-orbital-primary focus:ring-orbital-primary" /></label><label className="text-sm font-semibold text-orbital-text-primary">Status<select value={filters.status} onChange={(event) => onFilter('status', event.target.value)} className="mt-1 block w-full rounded-lg border-orbital-border bg-orbital-surface px-3 py-2 text-sm focus:border-orbital-primary focus:ring-orbital-primary">{statusOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div>
            {error && <div className="ledger-error mb-4" role="alert">{error}</div>}
            {loading ? <div className="ledger-state" role="status">Carregando transações…</div> : transactions.length === 0 ? <div className="ledger-empty rounded-2xl bg-orbital-background"><ReceiptText className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Nenhuma transação neste período.</p><p className="mt-1 text-sm text-orbital-text-secondary">Tente outra competência ou sincronize o cartão pelo Open Finance.</p></div> : <ul className="divide-y divide-orbital-border rounded-2xl border border-orbital-border">{transactions.map((transaction) => { const credit = transaction.effect === 'CREDIT'; return <li key={transaction.id} className="flex items-center gap-3 p-4"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${credit ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{credit ? <ArrowDownLeft className="h-4 w-4" aria-hidden="true" /> : <ArrowUpRight className="h-4 w-4" aria-hidden="true" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-orbital-text-primary">{transaction.description}</p><p className="mt-1 flex flex-wrap items-center gap-1 text-xs text-orbital-text-secondary"><CalendarDays className="h-3 w-3" aria-hidden="true" />{formatDateBR(transaction.transaction_date)}{transaction.installment && ` · Parcela ${transaction.installment.number}/${transaction.installment.total}`}</p></div><div className="text-right"><strong className={`block whitespace-nowrap text-sm ${credit ? 'text-emerald-700' : 'text-rose-700'}`}>{credit ? '+' : '-'} {money(transaction.amount)}</strong><Badge color={transaction.status === 'POSTED' ? 'success' : transaction.status === 'CANCELLED' ? 'gray' : 'warning'}>{transaction.status === 'POSTED' ? 'Realizada' : transaction.status === 'CANCELLED' ? 'Cancelada' : 'Prevista'}</Badge></div></li>; })}</ul>}
            {meta && meta.last_page > 1 && <div className="mt-4 flex items-center justify-between text-sm text-orbital-text-secondary"><span>{meta.from}–{meta.to} de {meta.total}</span><div className="flex gap-2"><Button color="light" size="xs" disabled={meta.current_page <= 1 || loading} onClick={() => onPage(meta.current_page - 1)}><ChevronLeft className="h-4 w-4" aria-hidden="true" /></Button><span className="flex items-center px-2 font-semibold">{meta.current_page}/{meta.last_page}</span><Button color="light" size="xs" disabled={meta.current_page >= meta.last_page || loading} onClick={() => onPage(meta.current_page + 1)}><ChevronRight className="h-4 w-4" aria-hidden="true" /></Button></div></div>}
        </ModalBody>
        <ModalFooter><Button color="light" onClick={onClose} disabled={loading}>Fechar</Button></ModalFooter>
    </Modal>;
}
