import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'flowbite-react';
import { CalendarDays, TrendingUp } from 'lucide-react';
import { Suspense } from 'react';
import Inputs from '@/Components/Inputs';

const money = (value) => (Number(value || 0) / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export default function InvestmentPositionModal({ open, onClose, investments, selectedInvestment, form, positions, onInvestmentChange, onSubmit, onEdit, onRemove, submitting, errors }) {
    return <Modal show={open} onClose={onClose} dismissible={!submitting} size="lg" className="wallet-modal">
        <ModalHeader className="wallet-modal__header"><span className="wallet-modal__mark"><TrendingUp className="h-5 w-5" aria-hidden="true" /></span><span className="wallet-modal__heading"><span className="wallet-modal__eyebrow">Evolução patrimonial</span><span className="wallet-modal__title">Lançar posição</span></span></ModalHeader>
        <form onSubmit={onSubmit}><ModalBody className="wallet-modal__body"><div className="wallet-modal__intro"><div><p className="wallet-modal__kicker">Registre o valor observado</p><p className="wallet-modal__description">O valor e a data são obrigatórios. Quantidade e preço unitário ajudam no detalhamento da posição.</p></div></div><Suspense fallback={<div className="h-64" aria-hidden="true" />}><Inputs.ErrorSummary errors={errors} /><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Inputs.Select name="investment_id" label="Investimento" value={investments.map((item) => ({ value: item.id, label: item.name })).find((option) => String(option.value) === String(form.data.investment_id)) ?? null} onChange={(option) => onInvestmentChange(option?.value ?? '')} errors={errors} options={investments.map((item) => ({ value: item.id, label: item.name }))} isClearable={false} required /></div><Inputs.Number name="value" label="Valor da posição" value={form.data.value} setData={form.setData} errors={errors} required /><Inputs.Flatpickr name="position_date" label="Data da posição" value={form.data.position_date} setData={form.setData} errors={errors} required /><Inputs.Number name="quantity" label="Quantidade (opcional)" value={form.data.quantity} setData={form.setData} errors={errors} format="decimal" maxDigits={8} /><Inputs.Number name="unit_price" label="Preço unitário (opcional)" value={form.data.unit_price} setData={form.setData} errors={errors} /></div></Suspense><div className="mt-6"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-orbital-primary-dark"><CalendarDays className="h-4 w-4" aria-hidden="true" />Histórico de {selectedInvestment?.name ?? 'posição'}</div>{positions.length === 0 ? <p className="text-sm text-orbital-text-secondary">Nenhuma posição lançada para este investimento.</p> : <div className="space-y-2">{positions.map((position) => <div key={position.id} className="flex items-center justify-between gap-3 rounded-lg border border-orbital-border px-3 py-2 text-sm"><span><strong className="block">{new Date(position.position_date + 'T12:00:00').toLocaleDateString('pt-BR')}</strong><small className="text-orbital-text-secondary">{position.quantity ? position.quantity + ' unidades' : 'Quantidade não informada'}</small></span><span className="flex items-center gap-2"><strong>{money(position.value)}</strong><Button type="button" color="light" size="xs" onClick={() => onEdit(position)}>Editar</Button><Button type="button" color="light" size="xs" onClick={() => onRemove(position)}>Excluir</Button></span></div>)}</div>}</div></ModalBody><ModalFooter className="wallet-modal__footer"><Button type="button" color="light" onClick={onClose} disabled={submitting}>Fechar</Button><Button type="submit" color="blue" disabled={submitting || !selectedInvestment}>{submitting ? 'Salvando…' : 'Salvar posição'}</Button></ModalFooter></form>
    </Modal>;
}
