import { Button } from 'flowbite-react';
import { Landmark, Pencil, Plus } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import AccountIcon from './Components/AccountIcon';
import AccountModal from './Components/AccountModal';
import AccountTransactionsModal from './Components/AccountTransactionsModal';
import TransactionModal from './Components/TransactionModal';
import useWallets from './Hooks/useWallets';

const accountTypeLabels = { CHECKING: 'Conta corrente', SAVINGS: 'Poupança', CASH: 'Dinheiro em espécie', INVESTMENT: 'Investimentos', DIGITAL_WALLET: 'Carteira digital' };

function AccountCard({ account, wallet, onEdit, onLaunch, onTransactions }) {
    return <article className="ledger-panel account-card"><div className="flex items-start justify-between gap-3"><AccountIcon bankCode={account.bank_code} />{account.is_default && <span className="rounded-full bg-orbital-primary-light px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-orbital-primary">Padrão</span>}</div><div className="mt-5 flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-lg font-bold text-orbital-primary-dark">{account.name}</h2><p className="mt-1 text-sm text-orbital-text-secondary">{wallet?.name ?? 'Carteira'} · {accountTypeLabels[account.type] ?? account.type}</p>{account.account_number && <p className="mt-3 text-sm text-orbital-text-secondary">Conta {account.account_number}</p>}</div><Button color="light" size="xs" onClick={() => onEdit(account)} aria-label={`Editar conta ${account.name}`}><Pencil className="h-4 w-4" aria-hidden="true" /></Button></div><div className="account-card__actions"><span>Ver histórico</span><div className="flex gap-2"><Button color="light" size="sm" onClick={() => onTransactions(account)}><Landmark className="mr-2 h-4 w-4" aria-hidden="true" />Movimentos</Button><Button color="blue" size="sm" onClick={() => onLaunch(account)}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Lançar</Button></div></div></article>;
}

export default function Accounts() {
    const accounts = useWallets();

    return <AppLayout><header className="ledger-header"><div><p className="ledger-eyebrow">Organização financeira</p><h1 className="ledger-heading">Suas contas.</h1><p className="mt-3 max-w-xl text-base leading-7 text-orbital-text-secondary">Veja onde seu dinheiro está e mantenha cada conta ligada à carteira certa.</p></div><Button color="blue" onClick={() => accounts.openAccountModal()} disabled={accounts.wallets.length === 0}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Nova conta</Button></header>{Object.keys(accounts.errors).length > 0 && <div className="ledger-error" role="alert">{Object.values(accounts.errors).flat()[0]}</div>}{accounts.loading ? <div className="ledger-panel ledger-state" role="status">Carregando contas…</div> : accounts.accounts.length === 0 ? <div className="ledger-panel ledger-empty" role="status"><Landmark className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Nenhuma conta criada ainda.</p><p className="mt-1 text-sm text-orbital-text-secondary">Use o botão acima para criar uma conta.</p></div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{accounts.accounts.map((account) => <AccountCard key={account.id} account={account} wallet={accounts.wallets.find((item) => item.id === account.wallet_id)} onEdit={accounts.openEditAccountModal} onLaunch={accounts.openTransactionModal} onTransactions={accounts.openAccountTransactions} />)}</div>}<AccountModal open={accounts.accountModalOpen} onClose={accounts.closeAccountModal} form={accounts.accountForm} wallet={accounts.selectedWalletForAccount} wallets={accounts.wallets} onWalletChange={accounts.selectWalletForAccount} onSubmit={accounts.submitAccount} submitting={accounts.accountSubmitting} errors={accounts.accountErrors} editing={accounts.editingAccount} /><TransactionModal open={accounts.transactionModalOpen} onClose={accounts.closeTransactionModal} form={accounts.transactionForm} accounts={accounts.selectedAccountForTransaction ? [accounts.selectedAccountForTransaction] : []} creditCards={[]} categories={accounts.transactionCategories} merchants={accounts.transactionMerchants} onCreateMerchant={() => {}} onSubmit={accounts.submitTransaction} submitting={accounts.transactionSubmitting} apiErrors={accounts.transactionErrors} editing={accounts.editingTransaction} /><AccountTransactionsModal account={accounts.selectedAccountForTransactions} transactions={accounts.accountTransactions} meta={accounts.accountTransactionsMeta} categories={accounts.transactionCategories} loading={accounts.accountTransactionsLoading} error={accounts.accountTransactionsError} filters={accounts.accountTransactionsFilters} onClose={accounts.closeAccountTransactions} onFilter={accounts.updateAccountTransactionsFilters} onPage={accounts.changeAccountTransactionsPage} onEditTransaction={accounts.requestEditTransaction} onEffectivate={accounts.effectivateTransaction} /></AppLayout>;
}
