import { Button } from 'flowbite-react';
import { CreditCard as CreditCardIcon, Pencil, Plus } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import CreditCardLogo from './Components/CreditCardIcon';
import CreditCardModal from './Components/CreditCardModal';
import useCreditCards from './Hooks/useCreditCards';

export default function CreditCards() {
    const cards = useCreditCards();
    return <AppLayout><header className="ledger-header"><div><p className="ledger-eyebrow">Meios de pagamento</p><h1 className="ledger-heading">Cartões de crédito.</h1><p className="mt-3 max-w-xl text-base leading-7 text-orbital-text-secondary">Organize limites, vencimentos e compras parceladas por carteira.</p></div><Button color="blue" onClick={() => cards.openModal()} disabled={cards.wallets.length === 0}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Novo cartão</Button></header>{Object.keys(cards.errors).length > 0 && <div className="ledger-error" role="alert">{Object.values(cards.errors).flat()[0]}</div>}{cards.loading ? <div className="ledger-panel ledger-state" role="status">Carregando cartões…</div> : cards.cards.length === 0 ? <div className="ledger-panel ledger-empty" role="status"><CreditCardIcon className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Nenhum cartão cadastrado.</p><p className="mt-1 text-sm text-orbital-text-secondary">Use o botão acima para criar seu primeiro cartão.</p></div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.cards.map((card) => <article key={card.id} className="ledger-panel"><div className="flex items-start justify-between gap-3"><CreditCardLogo institution={card.institution} /><Button color="light" size="xs" onClick={() => cards.openModal(card)} aria-label={`Editar cartão ${card.name}`}><Pencil className="h-4 w-4" aria-hidden="true" /></Button></div><h2 className="mt-5 text-lg font-bold text-orbital-primary-dark">{card.name}</h2><p className="mt-1 text-sm text-orbital-text-secondary">{cards.wallets.find((wallet) => wallet.id === card.wallet_id)?.name ?? 'Carteira'}</p>{card.institution && <p className="mt-1 text-xs text-orbital-text-secondary">{card.institution}</p>}<p className="mt-4 text-sm text-orbital-text-secondary">Limite: <strong className="text-orbital-text-primary">R$ {(Number(card.limit || 0) / 100).toFixed(2).replace('.', ',')}</strong></p><p className="mt-1 text-xs text-orbital-text-secondary">Fecha dia {card.closing_day} · vence dia {card.due_day}</p><span className={`mt-4 inline-flex rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${card.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{card.active ? 'Ativo' : 'Inativo'}</span></article>)}</div>}<CreditCardModal open={cards.modalOpen} onClose={cards.closeModal} form={cards.form} wallets={cards.wallets} accounts={cards.accounts} onWalletChange={cards.changeWallet} onSubmit={cards.submit} submitting={cards.submitting} errors={cards.errors} editing={cards.editingCard} /></AppLayout>;
}
