import { Button } from 'flowbite-react';
import { ArrowDownRight, ArrowUpRight, Pencil, Plus, TrendingUp, Trash2 } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import InvestmentModal from './Components/InvestmentModal';
import InvestmentIncome from './Components/InvestmentIncome';
import InvestmentFilters from './Components/InvestmentFilters';
import InvestmentYieldModal from './Components/InvestmentYieldModal';
import useInvestments from './Hooks/useInvestments';

const typeLabels = { STOCK: 'Ação', FUND: 'Fundo', FII: 'FII', FIXED_INCOME: 'Renda fixa', CRYPTO: 'Cripto', OTHER: 'Outro' };
const money = (value) => (Number(value || 0) / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

function InvestmentRow({ investment, onEdit, onRemove }) {
    const positive = Number(investment.profit_amount || 0) >= 0;
    return <div className="grid gap-3 border-b border-orbital-border px-4 py-4 last:border-b-0 sm:grid-cols-[1.5fr_1fr_1fr_1fr_auto] sm:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-orbital-primary-light text-orbital-primary"><TrendingUp className="h-4 w-4" aria-hidden="true" /></span><div className="min-w-0"><p className="truncate font-semibold text-orbital-primary-dark">{investment.name}</p><p className="truncate text-xs text-orbital-text-secondary">{investment.ticker || typeLabels[investment.type] || 'Investimento'}{investment.institution ? ` · ${investment.institution}` : ''}</p></div></div></div><div><p className="text-xs text-orbital-text-secondary">Investido</p><p className="font-semibold text-orbital-text-primary">{money(investment.invested_amount)}</p></div><div><p className="text-xs text-orbital-text-secondary">Valor atual</p><p className="font-semibold text-orbital-text-primary">{money(investment.current_value)}</p></div><div className={positive ? 'text-emerald-700' : 'text-red-600'}><p className="text-xs">Resultado</p><p className="flex items-center gap-1 font-semibold">{positive ? <ArrowUpRight className="h-4 w-4" aria-hidden="true" /> : <ArrowDownRight className="h-4 w-4" aria-hidden="true" />}{money(investment.profit_amount)} <span className="text-xs">({investment.profit_percentage}%)</span></p></div><div className="flex gap-1 sm:justify-end"><Button color="light" size="xs" onClick={() => onEdit(investment)} aria-label={`Editar investimento ${investment.name}`}><Pencil className="h-4 w-4" aria-hidden="true" /></Button><Button color="light" size="xs" onClick={() => onRemove(investment)} aria-label={`Excluir investimento ${investment.name}`}><Trash2 className="h-4 w-4 text-red-500" aria-hidden="true" /></Button></div></div>;
}

export default function Investments() {
    const investments = useInvestments();
    const wallet = investments.wallets.find((item) => String(item.id) === String(investments.selectedWalletId));
    const investedTotal = investments.investments.reduce((total, item) => total + Number(item.invested_amount || 0), 0);
    const currentTotal = investments.investments.reduce((total, item) => total + Number(item.current_value || 0), 0);
    const profit = currentTotal - investedTotal;
    const positive = profit >= 0;

    return <AppLayout><header className="ledger-header"><div><p className="ledger-eyebrow">Patrimônio em movimento</p><h1 className="ledger-heading">Seus investimentos.</h1><p className="mt-3 max-w-xl text-base leading-7 text-orbital-text-secondary">Veja onde seu dinheiro está trabalhando e acompanhe o resultado de cada posição.</p></div><Button color="blue" onClick={() => investments.openModal()} disabled={!wallet}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Novo investimento</Button></header>
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-orbital-border bg-orbital-surface px-4 py-3 shadow-sm"><label className="text-sm font-semibold text-orbital-primary-dark" htmlFor="investments-wallet">Carteira</label><select id="investments-wallet" value={investments.selectedWalletId} onChange={(event) => investments.selectWallet(event.target.value)} className="min-w-48 rounded-lg border-orbital-border bg-orbital-surface px-3 py-2 text-sm text-orbital-text-primary focus:border-orbital-primary focus:ring-orbital-primary"><option value="">Selecione uma carteira</option>{investments.wallets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
        {Object.keys(investments.errors).length > 0 && !investments.modalOpen && <div className="ledger-error" role="alert">{Object.values(investments.errors).flat()[0]}</div>}
        {investments.loading ? <div className="ledger-panel ledger-state" role="status">Carregando investimentos…</div> : !wallet ? <div className="ledger-panel ledger-empty" role="status"><TrendingUp className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Crie uma carteira para começar.</p></div> : <><section className="mb-6 grid gap-4 md:grid-cols-3"><div className="ledger-panel bg-orbital-primary-dark p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-orbital-primary-light/70">Valor atual</p><p className="mt-3 text-3xl font-bold">{money(currentTotal)}</p><p className="mt-1 text-sm text-white/60">{investments.investments.length} posições acompanhadas</p></div><div className="ledger-panel p-5"><p className="text-xs font-bold uppercase tracking-wider text-orbital-text-secondary">Total investido</p><p className="mt-3 text-3xl font-bold text-orbital-primary-dark">{money(investedTotal)}</p><p className="mt-1 text-sm text-orbital-text-secondary">Capital alocado</p></div><div className="ledger-panel p-5"><p className="text-xs font-bold uppercase tracking-wider text-orbital-text-secondary">Resultado acumulado</p><p className={`mt-3 text-3xl font-bold ${positive ? 'text-emerald-700' : 'text-red-600'}`}>{money(profit)}</p><p className="mt-1 text-sm text-orbital-text-secondary">{investedTotal ? `${((profit / investedTotal) * 100).toFixed(2).replace('.', ',')}% sobre o investido` : 'Sem base de comparação'}</p></div></section><section className="ledger-panel overflow-hidden"><div className="flex items-center justify-between border-b border-orbital-border px-4 py-4"><div><h2 className="font-bold text-orbital-primary-dark">Posições da carteira</h2><p className="mt-1 text-xs text-orbital-text-secondary">Atualize os valores quando quiser acompanhar sua evolução.</p></div></div>{investments.investments.length === 0 ? <div className="ledger-empty"><TrendingUp className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Nenhum investimento cadastrado.</p><Button color="blue" size="sm" className="mt-4" onClick={() => investments.openModal()}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Adicionar posição</Button></div> : investments.investments.map((item) => <InvestmentRow key={item.id} investment={item} onEdit={investments.openModal} onRemove={investments.remove} />)}</section></>}
        <InvestmentFilters investments={investments.allInvestments} filters={investments.investmentFilters} onChange={investments.updateInvestmentFilter} />
        <div className="mb-6 flex flex-wrap gap-2">{investments.investments.filter((item) => item.cdi_linked).map((item) => <Button key={item.id} color="light" size="xs" onClick={() => investments.openYields(item)}><TrendingUp className="mr-1 h-4 w-4" aria-hidden="true" />Ver evolução {item.ticker || item.name}</Button>)}</div>
        <InvestmentModal open={investments.modalOpen} onClose={investments.closeModal} form={investments.form} wallets={investments.wallets} onSubmit={investments.submit} submitting={investments.submitting} errors={investments.errors} editing={investments.editingInvestment} onLookupQuote={investments.lookupQuote} quoteLoading={investments.quoteLoading} quoteMessage={investments.quoteMessage} />
        <InvestmentYieldModal investment={investments.yieldInvestment} yields={investments.yields} loading={investments.yieldsLoading} onClose={investments.closeYields} />
        <InvestmentIncome income={investments.income} investments={investments.investments} filters={investments.incomeFilters} loading={investments.incomeLoading} onFilterChange={investments.updateIncomeFilters} onApply={investments.applyIncomeFilters} />
    </AppLayout>;
}
