import { Button, Modal, ModalBody, ModalFooter, ModalHeader } from 'flowbite-react';
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Layers3, Pencil, Plus, SlidersHorizontal, TrendingUp, Trash2 } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import InvestmentDashboard from './Components/InvestmentDashboard';
import InvestmentFilters from './Components/InvestmentFilters';
import InvestmentIncome from './Components/InvestmentIncome';
import InvestmentModal from './Components/InvestmentModal';
import InvestmentYieldModal from './Components/InvestmentYieldModal';
import useInvestments from './Hooks/useInvestments';

const typeLabels = { STOCK: 'Ação', FUND: 'Fundo', FII: 'FII', FIXED_INCOME: 'Renda fixa', CRYPTO: 'Cripto', OTHER: 'Outro' };
const money = (value) => (Number(value || 0) / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

function InvestmentRow({ investment, onEdit, onRemove }) {
    const positive = Number(investment.profit_amount || 0) >= 0;

    return <div className="investment-position-row"><div className="investment-position-row__name"><span className="investment-position-row__ticker">{investment.ticker || '—'}</span><span className="min-w-0"><strong className="block truncate">{investment.name}</strong><small>{typeLabels[investment.type] || investment.type}{investment.institution ? ` · ${investment.institution}` : ''}</small></span></div><div><small>Investido</small><strong>{money(investment.invested_amount)}</strong></div><div><small>Valor atual</small><strong>{money(investment.current_value)}</strong></div><div className={positive ? 'investment-value--positive' : 'investment-value--negative'}><small>Resultado</small><strong>{positive ? <ArrowUpRight aria-hidden="true" /> : <ArrowDownRight aria-hidden="true" />}{money(Math.abs(investment.profit_amount))} <em>({investment.profit_percentage}%)</em></strong></div><div className="investment-position-row__actions"><Button color="light" size="xs" onClick={() => onEdit(investment)} aria-label={`Editar investimento ${investment.name}`}><Pencil className="h-4 w-4" aria-hidden="true" /></Button><Button color="light" size="xs" onClick={() => onRemove(investment)} aria-label={`Excluir investimento ${investment.name}`}><Trash2 className="h-4 w-4 text-red-500" aria-hidden="true" /></Button></div></div>;
}

function PositionsModal({ open, investments, onClose, onEdit, onRemove }) {
    return <Modal show={open} onClose={onClose} size="7xl" className="investment-positions-modal wallet-modal"><ModalHeader className="wallet-modal__header"><span className="wallet-modal__mark"><Layers3 className="h-5 w-5" aria-hidden="true" /></span><span className="wallet-modal__heading"><span className="wallet-modal__eyebrow">Central de investimentos</span><span className="wallet-modal__title">Posições da carteira</span></span></ModalHeader><ModalBody className="wallet-modal__body investment-content-modal__body"><div className="wallet-modal__intro"><div><p className="wallet-modal__kicker">Patrimônio em movimento</p><p className="wallet-modal__description">Acompanhe ticker, tipo, instituição, capital e resultado de cada posição.</p></div></div>{investments.length === 0 ? <div className="ledger-empty"><TrendingUp className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Nenhuma posição encontrada.</p></div> : <div className="investment-position-list">{investments.map((investment) => <InvestmentRow key={investment.id} investment={investment} onEdit={onEdit} onRemove={onRemove} />)}</div>}</ModalBody><ModalFooter className="wallet-modal__footer"><Button color="light" className="wallet-modal__cancel" onClick={onClose}>Fechar</Button></ModalFooter></Modal>;
}

export default function Investments() {
    const investments = useInvestments();
    const wallet = investments.wallets.find((item) => String(item.id) === String(investments.selectedWalletId));

    return <AppLayout><header className="ledger-header"><div><p className="ledger-eyebrow">Patrimônio em movimento</p><h1 className="ledger-heading">Central de investimentos.</h1><p className="mt-3 max-w-xl text-base leading-7 text-orbital-text-secondary">Uma leitura operacional para saber onde seu capital está e qual posição merece atenção.</p></div><Button color="blue" onClick={() => investments.openModal()} disabled={!wallet}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Novo investimento</Button></header><div className="investment-wallet-bar"><label htmlFor="investments-wallet">Carteira em acompanhamento</label><select id="investments-wallet" value={investments.selectedWalletId} onChange={(event) => investments.selectWallet(event.target.value)}><option value="">Selecione uma carteira</option>{investments.wallets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{Object.keys(investments.errors).length > 0 && !investments.modalOpen && <div className="ledger-error" role="alert">{Object.values(investments.errors).flat()[0]}</div>}{investments.loading ? <div className="ledger-panel ledger-state" role="status">Carregando investimentos…</div> : !wallet ? <div className="ledger-panel ledger-empty" role="status"><TrendingUp className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Crie uma carteira para começar.</p></div> : <InvestmentDashboard investments={investments.allInvestments} income={investments.income} onOpenPositions={() => investments.setPositionsOpen(true)} onOpenFilters={() => investments.setFiltersOpen(true)} onOpenIncome={() => investments.setIncomeOpen(true)} onNewInvestment={() => investments.openModal()} />}
        <PositionsModal open={investments.positionsOpen} investments={investments.investments} onClose={() => investments.setPositionsOpen(false)} onEdit={investments.openModal} onRemove={investments.remove} />
        <Modal show={investments.filtersOpen} onClose={() => investments.setFiltersOpen(false)} size="md" className="investment-filters-modal wallet-modal"><ModalHeader className="wallet-modal__header"><span className="wallet-modal__mark"><SlidersHorizontal className="h-5 w-5" aria-hidden="true" /></span><span className="wallet-modal__heading"><span className="wallet-modal__eyebrow">Central de investimentos</span><span className="wallet-modal__title">Filtrar posições</span></span></ModalHeader><ModalBody className="wallet-modal__body"><div className="wallet-modal__intro"><div><p className="wallet-modal__kicker">Refine sua leitura</p><p className="wallet-modal__description">Escolha como deseja acompanhar as posições da carteira.</p></div></div><InvestmentFilters investments={investments.allInvestments} filters={investments.investmentFilters} onChange={investments.updateInvestmentFilter} /></ModalBody><ModalFooter className="wallet-modal__footer"><Button color="light" className="wallet-modal__cancel" onClick={() => investments.setFiltersOpen(false)}>Cancelar</Button><Button color="blue" className="wallet-modal__submit" onClick={() => investments.setFiltersOpen(false)}>Aplicar filtros</Button></ModalFooter></Modal>
        <Modal show={investments.incomeOpen} onClose={() => investments.setIncomeOpen(false)} dismissible size="7xl" className="investment-income-modal wallet-modal"><ModalHeader className="wallet-modal__header"><span className="wallet-modal__mark"><CircleDollarSign className="h-5 w-5" aria-hidden="true" /></span><span className="wallet-modal__heading"><span className="wallet-modal__eyebrow">Central de investimentos</span><span className="wallet-modal__title">Fluxo recebido</span></span></ModalHeader><ModalBody className="wallet-modal__body investment-content-modal__body"><div className="wallet-modal__intro"><div><p className="wallet-modal__kicker">Rendimentos recebidos</p><p className="wallet-modal__description">Consulte proventos e dividendos por período e posição.</p></div></div><InvestmentIncome income={investments.income} investments={investments.investments} filters={investments.incomeFilters} loading={investments.incomeLoading} onFilterChange={investments.updateIncomeFilters} onApply={investments.applyIncomeFilters} /></ModalBody><ModalFooter className="wallet-modal__footer"><Button color="light" className="wallet-modal__cancel" onClick={() => investments.setIncomeOpen(false)}>Fechar</Button></ModalFooter></Modal>
        <InvestmentModal open={investments.modalOpen} onClose={investments.closeModal} form={investments.form} wallets={investments.wallets} onSubmit={investments.submit} submitting={investments.submitting} errors={investments.errors} editing={investments.editingInvestment} onLookupQuote={investments.lookupQuote} quoteLoading={investments.quoteLoading} quoteMessage={investments.quoteMessage} />
        <InvestmentYieldModal investment={investments.yieldInvestment} yields={investments.yields} loading={investments.yieldsLoading} onClose={investments.closeYields} />
    </AppLayout>;
}
