import { Button } from 'flowbite-react';
import { Building2, CheckCircle2, Link2, RefreshCw, ShieldCheck, Unplug } from 'lucide-react';
import AppLayout from '@/Layouts/AppLayout';
import useOpenFinance from './Hooks/useOpenFinance';
import SyncConnectionModal from './Components/SyncConnectionModal';

const statusLabel = { CREATING: 'Conectando', UPDATING: 'Atualizando', UPDATED: 'Atualizada', LOGIN_ERROR: 'Ação necessária', WAITING_USER_INPUT: 'Aguardando confirmação', OUTDATED: 'Desatualizada' };
const money = (value) => (Number(value || 0) / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

function InstitutionLogo({ item }) {
    return <span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-orbital-primary-light text-orbital-primary">{item.connector_logo ? <img src={item.connector_logo} alt="" className="h-full w-full object-contain" /> : <Building2 className="h-6 w-6" aria-hidden="true" />}</span>;
}

export default function OpenFinance() {
    const finance = useOpenFinance();
    const wallet = finance.wallets.find((item) => String(item.id) === String(finance.selectedWalletId));

    return <AppLayout><header className="ledger-header"><div><p className="ledger-eyebrow">Dados sempre seus</p><h1 className="ledger-heading">Open Finance.</h1><p className="mt-3 max-w-xl text-base leading-7 text-orbital-text-secondary">Conecte suas instituições com segurança e acompanhe suas contas em um só lugar.</p></div><Button color="blue" onClick={finance.connect} disabled={!wallet || finance.connecting}>{finance.connecting ? 'Abrindo conexão…' : <><Link2 className="mr-2 h-4 w-4" aria-hidden="true" />Conectar instituição</>}</Button></header>
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-orbital-border bg-orbital-surface px-4 py-3 shadow-sm"><label className="text-sm font-semibold text-orbital-primary-dark" htmlFor="open-finance-wallet">Salvar contas em</label><select id="open-finance-wallet" value={finance.selectedWalletId} onChange={(event) => finance.setSelectedWalletId(event.target.value)} className="min-w-48 rounded-lg border-orbital-border bg-orbital-surface px-3 py-2 text-sm text-orbital-text-primary focus:border-orbital-primary focus:ring-orbital-primary"><option value="">Selecione uma carteira</option>{finance.wallets.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
        <section className="mb-6 grid gap-4 md:grid-cols-3"><div className="ledger-panel bg-orbital-primary-dark p-5 text-white"><ShieldCheck className="h-5 w-5 text-orbital-accent" aria-hidden="true" /><p className="mt-4 text-sm leading-6 text-white/75">Suas credenciais são informadas diretamente no ambiente seguro da instituição.</p></div><div className="ledger-panel p-5"><p className="text-xs font-bold uppercase tracking-wider text-orbital-text-secondary">Instituições</p><p className="mt-3 text-3xl font-bold text-orbital-primary-dark">{finance.items.length}</p><p className="mt-1 text-sm text-orbital-text-secondary">conexões acompanhadas</p></div><div className="ledger-panel p-5"><p className="text-xs font-bold uppercase tracking-wider text-orbital-text-secondary">Contas sincronizadas</p><p className="mt-3 text-3xl font-bold text-orbital-primary-dark">{finance.items.reduce((total, item) => total + (item.accounts?.length ?? 0), 0)}</p><p className="mt-1 text-sm text-orbital-text-secondary">prontas para usar</p></div></section>
        {Object.keys(finance.errors).length > 0 && <div className="ledger-error" role="alert">{Object.values(finance.errors).flat()[0]}</div>}
        {finance.loading ? <div className="ledger-panel ledger-state" role="status">Carregando conexões…</div> : finance.items.length === 0 ? <div className="ledger-panel ledger-empty" role="status"><Link2 className="mx-auto h-8 w-8 text-orbital-primary" aria-hidden="true" /><p className="mt-3 font-semibold text-orbital-primary-dark">Nenhuma instituição conectada.</p><p className="mt-1 text-sm text-orbital-text-secondary">Conecte seu banco para trazer suas contas para cá.</p></div> : <div className="grid gap-4 lg:grid-cols-2">{finance.items.map((item) => <article key={item.id} className="ledger-panel p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><InstitutionLogo item={item} /><div className="min-w-0"><h2 className="truncate text-lg font-bold text-orbital-primary-dark">{item.connector_name || 'Instituição financeira'}</h2><p className="mt-1 flex items-center gap-1 text-xs text-orbital-text-secondary"><span className={`h-2 w-2 rounded-full ${item.status === 'UPDATED' ? 'bg-emerald-500' : item.status === 'LOGIN_ERROR' ? 'bg-red-500' : 'bg-orbital-accent'}`} />{statusLabel[item.status] || item.status || 'Aguardando sincronização'}</p></div></div><div className="flex gap-1"><Button color="light" size="xs" onClick={() => finance.openSync(item)} aria-label={`Sincronizar ${item.connector_name || 'instituição'}`}><RefreshCw className="h-4 w-4" /></Button><Button color="light" size="xs" onClick={() => finance.disconnect(item)} aria-label={`Desconectar ${item.connector_name || 'instituição'}`}><Unplug className="h-4 w-4" aria-hidden="true" /></Button></div></div><div className="mt-5 space-y-2">{item.accounts?.length ? item.accounts.map((account) => <div key={account.id} className="flex items-center justify-between rounded-xl bg-orbital-background px-3 py-3"><div className="flex min-w-0 items-center gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" aria-hidden="true" /><span className="truncate text-sm font-semibold text-orbital-text-primary">{account.name}</span></div><strong className="ml-3 shrink-0 text-sm text-orbital-primary-dark">{money(account.pluggy_balance)}</strong></div>) : <p className="rounded-xl bg-orbital-background px-3 py-3 text-sm text-orbital-text-secondary">Aguardando a primeira sincronização da instituição.</p>}</div><div className="mt-4 flex items-center justify-between text-xs text-orbital-text-secondary"><span>{item.last_synced_at ? `Sincronizada em ${new Date(item.last_synced_at).toLocaleString('pt-BR')}` : 'Sincronização pendente'}</span><RefreshCw className="h-4 w-4" aria-hidden="true" /></div></article>)}</div>}
        <SyncConnectionModal open={Boolean(finance.syncingConnection)} onClose={finance.closeSync} form={{ ...finance.syncForm, setPeriod: (period) => finance.setSyncForm((current) => ({ ...current, period })), setFrom: (from) => finance.setSyncForm((current) => ({ ...current, from })), setTo: (to) => finance.setSyncForm((current) => ({ ...current, to })) }} onSubmit={finance.sync} submitting={finance.syncing} errors={finance.errors} />
    </AppLayout>;
}
